version: '3.8'

services:
  php-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: phpchallenge:latest
    container_name: php-web
    ports:
      - "80:80"
    volumes:
      - ./uploads:/var/www/html/uploads
    networks:
      - php-net

volumes:
  uploads:

networks:
  php-net:
    driver: bridge
